//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rensoft.Hosting.DataAccess.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspCommandCarrier", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    [System.SerializableAttribute()]
    public partial class RhspCommandCarrier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspCommand CommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandContext ContextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspCommand Command {
            get {
                return this.CommandField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandField, value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandContext Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspCommand", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    [System.SerializableAttribute()]
    public partial class RhspCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspParameterCollection ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandText {
            get {
                return this.CommandTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandTextField, value) != true)) {
                    this.CommandTextField = value;
                    this.RaisePropertyChanged("CommandText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspParameterCollection Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspCommandContext", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    [System.SerializableAttribute()]
    public partial class RhspCommandContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HostingUserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HostingUserID {
            get {
                return this.HostingUserIDField;
            }
            set {
                if ((this.HostingUserIDField.Equals(value) != true)) {
                    this.HostingUserIDField = value;
                    this.RaisePropertyChanged("HostingUserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspParameterCollection", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    [System.SerializableAttribute()]
    public partial class RhspParameterCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, Rensoft.Hosting.DataAccess.ServiceReference.RhspParameter> TableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, Rensoft.Hosting.DataAccess.ServiceReference.RhspParameter> Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspParameter", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.FtpUser[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.FtpUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Password))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusActionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusCondition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsZone))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsRecord[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsRecordType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Website))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsZone[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHost[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHost))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHostProtocol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisSite))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisManagedPipelineMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplate[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplateAccess))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandCarrier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspParameterCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspDataMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteDeleteResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.CustomerDeleteResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, Rensoft.Hosting.DataAccess.ServiceReference.RhspParameter>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class RhspParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataMode DataModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] RawValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataMode DataMode {
            get {
                return this.DataModeField;
            }
            set {
                if ((this.DataModeField.Equals(value) != true)) {
                    this.DataModeField = value;
                    this.RaisePropertyChanged("DataMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTypeName {
            get {
                return this.DataTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTypeNameField, value) != true)) {
                    this.DataTypeNameField = value;
                    this.RaisePropertyChanged("DataTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] RawValue {
            get {
                return this.RawValueField;
            }
            set {
                if ((object.ReferenceEquals(this.RawValueField, value) != true)) {
                    this.RawValueField = value;
                    this.RaisePropertyChanged("RawValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class Customer : Rensoft.Hosting.DataAccess.ServiceReference.RhspData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FtpEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.FtpUser[] FtpUserArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FtpEnabled {
            get {
                return this.FtpEnabledField;
            }
            set {
                if ((this.FtpEnabledField.Equals(value) != true)) {
                    this.FtpEnabledField = value;
                    this.RaisePropertyChanged("FtpEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.FtpUser[] FtpUserArray {
            get {
                return this.FtpUserArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FtpUserArrayField, value) != true)) {
                    this.FtpUserArrayField = value;
                    this.RaisePropertyChanged("FtpUserArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspData", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsZone))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Website))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHost))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Customer))]
    public partial class RhspData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID DataIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID DataID {
            get {
                return this.DataIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DataIDField, value) != true)) {
                    this.DataIDField = value;
                    this.RaisePropertyChanged("DataID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FtpUser", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class FtpUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID DataIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.Password PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID DataID {
            get {
                return this.DataIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DataIDField, value) != true)) {
                    this.DataIDField = value;
                    this.RaisePropertyChanged("DataID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.Password Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingAction {
            get {
                return this.PendingActionField;
            }
            set {
                if ((this.PendingActionField.Equals(value) != true)) {
                    this.PendingActionField = value;
                    this.RaisePropertyChanged("PendingAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Password", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class Password : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerStatusActionResult", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class ServerStatusActionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserMessage {
            get {
                return this.UserMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.UserMessageField, value) != true)) {
                    this.UserMessageField = value;
                    this.RaisePropertyChanged("UserMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerStatusElement", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class ServerStatusElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusCondition ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCommand {
            get {
                return this.ActionCommandField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCommandField, value) != true)) {
                    this.ActionCommandField = value;
                    this.RaisePropertyChanged("ActionCommand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionText {
            get {
                return this.ActionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTextField, value) != true)) {
                    this.ActionTextField = value;
                    this.RaisePropertyChanged("ActionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusCondition Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((this.ConditionField.Equals(value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerStatusCondition", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    public enum ServerStatusCondition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DnsZone", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class DnsZone : Rensoft.Hosting.DataAccess.ServiceReference.RhspData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultTtlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.DnsRecord[] RecordArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID WebsiteIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultTtl {
            get {
                return this.DefaultTtlField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultTtlField, value) != true)) {
                    this.DefaultTtlField = value;
                    this.RaisePropertyChanged("DefaultTtl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingAction {
            get {
                return this.PendingActionField;
            }
            set {
                if ((this.PendingActionField.Equals(value) != true)) {
                    this.PendingActionField = value;
                    this.RaisePropertyChanged("PendingAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.DnsRecord[] RecordArray {
            get {
                return this.RecordArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordArrayField, value) != true)) {
                    this.RecordArrayField = value;
                    this.RaisePropertyChanged("RecordArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DnsRecord", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class DnsRecord : Rensoft.Hosting.DataAccess.ServiceReference.RhspData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.DnsRecordType RecordTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TtlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingAction {
            get {
                return this.PendingActionField;
            }
            set {
                if ((this.PendingActionField.Equals(value) != true)) {
                    this.PendingActionField = value;
                    this.RaisePropertyChanged("PendingAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.DnsRecordType RecordType {
            get {
                return this.RecordTypeField;
            }
            set {
                if ((this.RecordTypeField.Equals(value) != true)) {
                    this.RecordTypeField = value;
                    this.RaisePropertyChanged("RecordType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ttl {
            get {
                return this.TtlField;
            }
            set {
                if ((object.ReferenceEquals(this.TtlField, value) != true)) {
                    this.TtlField = value;
                    this.RaisePropertyChanged("Ttl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DnsRecordType", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    public enum DnsRecordType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MX = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        A = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNAME = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TXT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PTR = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Website", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class Website : Rensoft.Hosting.DataAccess.ServiceReference.RhspData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.DnsZone[] DnsZoneArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHost[] HostArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisSite IisSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID PrimaryHostIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplate[] SecurityArrayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.DnsZone[] DnsZoneArray {
            get {
                return this.DnsZoneArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.DnsZoneArrayField, value) != true)) {
                    this.DnsZoneArrayField = value;
                    this.RaisePropertyChanged("DnsZoneArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHost[] HostArray {
            get {
                return this.HostArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.HostArrayField, value) != true)) {
                    this.HostArrayField = value;
                    this.RaisePropertyChanged("HostArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisSite IisSite {
            get {
                return this.IisSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.IisSiteField, value) != true)) {
                    this.IisSiteField = value;
                    this.RaisePropertyChanged("IisSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID PrimaryHostID {
            get {
                return this.PrimaryHostIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryHostIDField, value) != true)) {
                    this.PrimaryHostIDField = value;
                    this.RaisePropertyChanged("PrimaryHostID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplate[] SecurityArray {
            get {
                return this.SecurityArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityArrayField, value) != true)) {
                    this.SecurityArrayField = value;
                    this.RaisePropertyChanged("SecurityArray");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteHost", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class WebsiteHost : Rensoft.Hosting.DataAccess.ServiceReference.RhspData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHostProtocol ProtocolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID WebsiteIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingAction {
            get {
                return this.PendingActionField;
            }
            set {
                if ((this.PendingActionField.Equals(value) != true)) {
                    this.PendingActionField = value;
                    this.RaisePropertyChanged("PendingAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHostProtocol Protocol {
            get {
                return this.ProtocolField;
            }
            set {
                if ((this.ProtocolField.Equals(value) != true)) {
                    this.ProtocolField = value;
                    this.RaisePropertyChanged("Protocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteHostProtocol", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    public enum WebsiteHostProtocol : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Http = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Https = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteIisSite", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class WebsiteIisSite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationPoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.Password IdentityPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentitySidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisManagedPipelineMode ManagedPipelineModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagedRuntimeVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisMode ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedirectUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationPoolName {
            get {
                return this.ApplicationPoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationPoolNameField, value) != true)) {
                    this.ApplicationPoolNameField = value;
                    this.RaisePropertyChanged("ApplicationPoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.Password IdentityPassword {
            get {
                return this.IdentityPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityPasswordField, value) != true)) {
                    this.IdentityPasswordField = value;
                    this.RaisePropertyChanged("IdentityPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentitySid {
            get {
                return this.IdentitySidField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentitySidField, value) != true)) {
                    this.IdentitySidField = value;
                    this.RaisePropertyChanged("IdentitySid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityUserName {
            get {
                return this.IdentityUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityUserNameField, value) != true)) {
                    this.IdentityUserNameField = value;
                    this.RaisePropertyChanged("IdentityUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisManagedPipelineMode ManagedPipelineMode {
            get {
                return this.ManagedPipelineModeField;
            }
            set {
                if ((this.ManagedPipelineModeField.Equals(value) != true)) {
                    this.ManagedPipelineModeField = value;
                    this.RaisePropertyChanged("ManagedPipelineMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagedRuntimeVersion {
            get {
                return this.ManagedRuntimeVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagedRuntimeVersionField, value) != true)) {
                    this.ManagedRuntimeVersionField = value;
                    this.RaisePropertyChanged("ManagedRuntimeVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisMode Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedirectUrl {
            get {
                return this.RedirectUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.RedirectUrlField, value) != true)) {
                    this.RedirectUrlField = value;
                    this.RaisePropertyChanged("RedirectUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiteID {
            get {
                return this.SiteIDField;
            }
            set {
                if ((this.SiteIDField.Equals(value) != true)) {
                    this.SiteIDField = value;
                    this.RaisePropertyChanged("SiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName {
            get {
                return this.SiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteNameField, value) != true)) {
                    this.SiteNameField = value;
                    this.RaisePropertyChanged("SiteName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteIisManagedPipelineMode", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    public enum WebsiteIisManagedPipelineMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integrated = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Classic = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteIisMode", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    public enum WebsiteIisMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standard = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Redirect = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityTemplate", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    [System.SerializableAttribute()]
    public partial class SecurityTemplate : Rensoft.Hosting.DataAccess.ServiceReference.RhspData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplateAccess AccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelativePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseIisIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID WebsiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WriteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplateAccess Access {
            get {
                return this.AccessField;
            }
            set {
                if ((this.AccessField.Equals(value) != true)) {
                    this.AccessField = value;
                    this.RaisePropertyChanged("Access");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Delete {
            get {
                return this.DeleteField;
            }
            set {
                if ((this.DeleteField.Equals(value) != true)) {
                    this.DeleteField = value;
                    this.RaisePropertyChanged("Delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction PendingAction {
            get {
                return this.PendingActionField;
            }
            set {
                if ((this.PendingActionField.Equals(value) != true)) {
                    this.PendingActionField = value;
                    this.RaisePropertyChanged("PendingAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Read {
            get {
                return this.ReadField;
            }
            set {
                if ((this.ReadField.Equals(value) != true)) {
                    this.ReadField = value;
                    this.RaisePropertyChanged("Read");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelativePath {
            get {
                return this.RelativePathField;
            }
            set {
                if ((object.ReferenceEquals(this.RelativePathField, value) != true)) {
                    this.RelativePathField = value;
                    this.RaisePropertyChanged("RelativePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseIisIdentity {
            get {
                return this.UseIisIdentityField;
            }
            set {
                if ((this.UseIisIdentityField.Equals(value) != true)) {
                    this.UseIisIdentityField = value;
                    this.RaisePropertyChanged("UseIisIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID WebsiteID {
            get {
                return this.WebsiteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteIDField, value) != true)) {
                    this.WebsiteIDField = value;
                    this.RaisePropertyChanged("WebsiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Write {
            get {
                return this.WriteField;
            }
            set {
                if ((this.WriteField.Equals(value) != true)) {
                    this.WriteField = value;
                    this.RaisePropertyChanged("Write");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityTemplateAccess", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Data")]
    public enum SecurityTemplateAccess : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Allow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deny = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspDataID", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    [System.SerializableAttribute()]
    public partial class RhspDataID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChildPendingAction", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    public enum ChildPendingAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Create = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Discard = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspDataMode", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    public enum RhspDataMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Array = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RhspCommandResponse", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.FtpUser[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.FtpUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Password))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusActionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ServerStatusCondition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsZone))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsRecord[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsRecordType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.Website))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.DnsZone[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHost[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHost))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteHostProtocol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisSite))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisManagedPipelineMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteIisMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplate[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.SecurityTemplateAccess))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspDataID))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.ChildPendingAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandCarrier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspParameterCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspDataMode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.WebsiteDeleteResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Rensoft.Hosting.DataAccess.ServiceReference.CustomerDeleteResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, Rensoft.Hosting.DataAccess.ServiceReference.RhspParameter>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class RhspCommandResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Rensoft.Hosting.DataAccess.ServiceReference.RhspDataMode DataModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] RawDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspDataMode DataMode {
            get {
                return this.DataModeField;
            }
            set {
                if ((this.DataModeField.Equals(value) != true)) {
                    this.DataModeField = value;
                    this.RaisePropertyChanged("DataMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] RawData {
            get {
                return this.RawDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RawDataField, value) != true)) {
                    this.RawDataField = value;
                    this.RaisePropertyChanged("RawData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteDeleteResult", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Managers")]
    [System.SerializableAttribute()]
    public partial class WebsiteDeleteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDeleteResult", Namespace="http://schemas.datacontract.org/2004/07/Rensoft.Hosting.Server.Managers")]
    [System.SerializableAttribute()]
    public partial class CustomerDeleteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRhspService")]
    public interface IRhspService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRhspService/GetCommandResponse", ReplyAction="http://tempuri.org/IRhspService/GetCommandResponseResponse")]
        Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandResponse GetCommandResponse(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandCarrier carrier);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRhspServiceChannel : Rensoft.Hosting.DataAccess.ServiceReference.IRhspService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RhspServiceClient : System.ServiceModel.ClientBase<Rensoft.Hosting.DataAccess.ServiceReference.IRhspService>, Rensoft.Hosting.DataAccess.ServiceReference.IRhspService {
        
        public RhspServiceClient() {
        }
        
        public RhspServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RhspServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RhspServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RhspServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandResponse GetCommandResponse(Rensoft.Hosting.DataAccess.ServiceReference.RhspCommandCarrier carrier) {
            return base.Channel.GetCommandResponse(carrier);
        }
    }
}
