//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostingSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HostingSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] BIND9_5_0_P2_W2 {
            get {
                object obj = ResourceManager.GetObject("BIND9_5_0_P2_W2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] filezilla_server_0_9_28 {
            get {
                object obj = ResourceManager.GetObject("filezilla_server_0_9_28", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HostingManagerSetup {
            get {
                object obj = ResourceManager.GetObject("HostingManagerSetup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HostingServerSetup {
            get {
                object obj = ResourceManager.GetObject("HostingServerSetup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ICSharpCode_SharpZipLib_dll {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_SharpZipLib_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_WindowsInstaller_dll {
            get {
                object obj = ResourceManager.GetObject("Interop_WindowsInstaller_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon Rensoft {
            get {
                object obj = ResourceManager.GetObject("Rensoft", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] Rensoft_dll {
            get {
                object obj = ResourceManager.GetObject("Rensoft_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Rensoft_Hosting_DataAccess_dll {
            get {
                object obj = ResourceManager.GetObject("Rensoft_Hosting_DataAccess_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Rensoft_Hosting_dll {
            get {
                object obj = ResourceManager.GetObject("Rensoft_Hosting_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Rensoft_Hosting_Setup_exe {
            get {
                object obj = ResourceManager.GetObject("Rensoft_Hosting_Setup_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&quot;applicationSettings&quot; type=&quot;System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///            &lt;section name=&quot;Rensoft.Hosting.Setup.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; requirePermission=&quot;false&quot; /&gt;
        ///        &lt;/sectionGroup&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rensoft_Hosting_Setup_exe_config {
            get {
                return ResourceManager.GetString("Rensoft_Hosting_Setup_exe_config", resourceCulture);
            }
        }
        
        internal static byte[] Rensoft_ServerManagement_dll {
            get {
                object obj = ResourceManager.GetObject("Rensoft_ServerManagement_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Rensoft_Windows_Forms_dll {
            get {
                object obj = ResourceManager.GetObject("Rensoft_Windows_Forms_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
